# Generated by Django 2.2.4 on 2019-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddescription',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
