# Generated by Django 2.2.5 on 2019-09-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CautionMessage',
        ),
        migrations.DeleteModel(
            name='RiskRatingValue',
        ),
    ]
