# Generated by Django 2.2.4 on 2019-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0002_auto_20190829_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddescription',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
