# Generated by Django 2.2.4 on 2019-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0003_auto_20190829_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForageHeightOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
