# Generated by Django 2.2.5 on 2019-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0003_auto_20190925_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalAreaOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='forageheightoption',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='watertabledepthoption',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
