# Generated by Django 2.2.4 on 2019-08-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0004_forageheightoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTableDepthOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
